### ISSUE TITLE
upgrade to docusaurus3.0

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#104]
**What type of your feature request?**  

refer to: https://docusaurus.io/docs/migration/v3

**Comment by zhaojing1987** [comment]
已通过命令：
```
yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest
```
升级到：3.0.1

通过package.json查看：
  "dependencies": {
    "@docusaurus/core": "^3.0.1",
    "@docusaurus/preset-classic": "^3.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  
  为了适应版本，同时将react和react-dom升级到了18.2.0
