### ISSUE TITLE
create applist.md file from Contentful

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#108]
**What type of your feature request?**  

I want to my applist documentation file like this: https://aws.amazon.com/cn/documentation-overview/

suggest chatgpt question: 我有一个json 文件，需要将其中的数据提取成为一个 md 文件。实现可以模板化吗？

**Comment by qiaofeng1227** [comment]
You can get json from https://w9artifact.blob.core.windows.net/release/websoft9/plugin/media/media-latest.zip

**Comment by chendelin1982** [comment]
```
# 应用

下面是 Websoft9 应用商店中所有应用的文档：

## 设计创作

- [apex](/apps/apex)
- [apitable](/apps/apitable)

## IT 监控运维

- [awx](/apps/awx)
- [gitlab](/apps/gitlab)

```

**Comment by chendelin1982** [comment]
优化

- 应用在目录中去重（优先归属需处理）
- 目录排序

**Comment by chendelin1982** [comment]
add # title and description at the top of md file
```
# 应用

我们提供了数百个热门开源应用的自动化部署包，请点击下面的类目详细了解。

如果您期望的应用不在类目中，欢迎给我们反馈。如果您是优质应用供应商，欢迎[加入](http://www.websoft9.com)到我们的目录中来。


# Apps

Docs of hundreds of pre-packaged apps below
```

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/doc.websoft9.com/assets/16741975/fccc1aba-38d8-493d-804d-2b0fee4e326a)
