### ISSUE TITLE
can not show release new WeChat Group feature in chinese

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/doc.websoft9.com#113]
https://www.websoft9.com/en-US/contact-us

english

![image](https://github.com/Websoft9/doc.websoft9.com/assets/43192516/432cf119-5bc0-46a8-aad3-a193c705bb8c)

chinese

![image](https://github.com/Websoft9/doc.websoft9.com/assets/43192516/eb98d39c-8664-407c-92ee-226e76a45ff0)

**Comment by qiaofeng1227** [comment]
官网是编译出静态页面的，加上blog文章，app的分类产生的页面，有个几百个页面，然后又分中英文页面，在微软全球缓存同步上，肯定是有时间的

**Comment by qiaofeng1227** [comment]
有时候，中文页面刷新的时候，也是出现了一些新增的图片，然后再消失的，这是为什么

**Comment by chendelin1982** [comment]
- 缓存
- 源
- cdn

三者如何工作的？
