### ISSUE TITLE
Ghost Moodle 准确性提出建议

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/doc.websoft9.com#123]
1.   Ghost 是一个 博客创作与付费阅读平台，它被用于 企业建站 等场景。Ghost 是一款功能强大的知识内容变现软件，供新媒体创作者围绕其内容发布、分享和发展业务。----这个描述不通畅，请优化一下。

2.   Moodle 是一个面向全球用户的开源在线教育系统，它被用于在线学习等场景，是全球各大中学院校建立开放式课程系统的首选软件。----是说 全球的大学和中学，还是全球的中学院校？

**Comment by chendelin1982** [comment]
- Ghost 是一个开源的博客平台，专为在线内容创作和内容出版而设计。它旨在提供一个简洁、快速且功能强大的工具，帮助写作者、博主和媒体机构发布和管理内容，它的订阅付费阅读功能还可以方便的帮助内容结构变现。

- Moodle 是一个流行的开源学习管理系统（LMS），用于创建和管理在线课程和学习内容。它广泛应用于高等院校、教育机构、企业培训和其他需要在线学习管理的平台。

@qiaofeng1227  update to Contentful

**Comment by qiaofeng1227** [comment]
模板以外的内容已经修改。
