### ISSUE TITLE
文档系统切换细节工作

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#14]
**What type of your feature request?**  

切换到新文档后，出现的问题如下：

## 问题

- [ ] 所有运行环境类的路由变更为一个统一入口：https://support.websoft9.com/docs/runtime
- [ ] 官网到文档的链接失效
- [ ] 中文文档 /zh 导致无法访问
- [ ] 原英文文档连接打开后是中文
- [ ] Mariadb 与 MySQL 合并, 路径统一为 mysql
- [ ] https://support.websoft9.com/docs/legal/privacy.html  变更为 https://support.websoft9.com/docs/legal/privacy

## 平台检查

- [ ] 阿里云 文档
- [ ] 华为云 文档
- [ ] 腾讯云 文档
- [ ] Azure 技术支持，隐私，文档
- [ ] AWS 技术支持，文档
- [ ] Alibaba Cloud 文档，EULA
- [ ] HUAWEI CLOUD 文档

**Comment by chendelin1982** [comment]
中文文档 /zh 问题可以通过 Azure CDN 规则引擎处理
![image](https://user-images.githubusercontent.com/16741975/177271606-8cdb70ce-ee5a-4497-bade-b890084f9987.png)

**Comment by qiaofeng1227** [comment]
[Verizon Premium Azure CDN 规则引擎](https://docs.microsoft.com/zh-cn/azure/cdn/cdn-verizon-premium-rules-engine-reference-features?toc=%2Fazure%2Ffrontdoor%2FTOC.json)
