### ISSUE TITLE
The English doc of Tensorflow has some errors.

### ISSUE THREAD

**Issue by HTGZYY** [Websoft9/doc.websoft9.com#156]
**What type of your feature request?**  

- [ ] Add new features
- [√ ] Improve current features

**Is your feature request related to a problem? Please describe.**  
"**TensorFlow is an end-to-end open source machine learning platform. **" This sentence is not bolded due to the ”.“ It's not bolded.

**Describe the solution you'd like**  
Remove the ". "

**Comment by chendelin1982** [comment]
solved, thank you
