### ISSUE TITLE
Enable Cloudflare Web Analytics

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/doc.websoft9.com#163]
迁移至 [Cloudflare](https://www.cloudflare.com/)，通过 [Cloudflare](https://www.cloudflare.com/) 自带的静态网站统计功能

**Comment by chendelin1982** [comment]
迁移至 [Cloudflare](https://www.cloudflare.com/)，通过 [Cloudflare](https://www.cloudflare.com/) 自带的静态网站统计功能

**Comment by chendelin1982** [comment]
Cloudflare automaticlly Analytics
