### ISSUE TITLE
transfer docs/site/artifact to Cloudflare

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#198]
**What type of your feature request?**  

- [x] prepare Cloudflare account
- [x] change github action of transfer docs to Cloudflare
- [x] test `apidocs` build at websoft9 repository, it need to publish to `docs pages` at Cloudflase
- [x] test artifact (keys add to zoho, domain `artifact.websoft9.com`)
- [x] transfer artifacts from azure blob to r2 by tool like `rclone`

**Comment by chendelin1982** [comment]
closed

**Comment by qiaofeng1227** [comment]
refer to： https://github.com/Websoft9/websoft9/issues/530
