### ISSUE TITLE
trailing slash issue, links error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#249]
https://support.websoft9.com/docs/moodle/ [默认账号和密码](https://support.websoft9.com/docs/user/credentials) directly open 404, but open at new tab page is OK

访问 https://support.websoft9.com/docs/moodle/ 时，浏览器会将相对路径 ./user/credentials 解析为 https://support.websoft9.com/docs/moodle/user/credentials。

访问 https://support.websoft9.com/docs/moodle 时，浏览器会将相对路径 ./user/credentials 解析为 https://support.websoft9.com/docs/user/credentials

**Comment by chendelin1982** [comment]
访问 https://support.websoft9.com/docs/moodle/ 时，浏览器会将相对路径 ./user/credentials 解析为 https://support.websoft9.com/docs/moodle/user/credentials。

访问 https://support.websoft9.com/docs/moodle 时，浏览器会将相对路径 ./user/credentials 解析为 https://support.websoft9.com/docs/user/credentials

**Comment by zhaojing1987** [comment]
问题：Docusaurus 中，URL 末尾的斜杠可能会影响相对路径加载资源出错
方案：将所有url中末尾的/ 去掉
实施：新增js文件：src/theme/Layout.js
```
import { useLocation } from '@docusaurus/router';
import OriginalLayout from '@theme-original/Layout';
import React, { useEffect } from 'react';
import { useHistory } from 'react-router-dom';

function useRemoveTrailingSlash() {
    const location = useLocation();
    const history = useHistory();

    useEffect(() => {
        const { pathname, search, hash } = location;
        if (pathname.length > 1 && pathname.endsWith('/')) {
            const newPath = pathname.slice(0, -1) + search + hash;
            console.log(`old pathname: ${pathname}, Redirecting to: ${newPath}`);
            // 使用 history.replace 以避免页面刷新
            history.replace(newPath);
        }
    }, [location, history]);
}

export default function Layout(props) {
    useRemoveTrailingSlash();

    return <OriginalLayout {...props} />;
}
```
- 使用 useEffect 钩子：确保在每次页面加载和路由变化时检查并处理 URL。
- 使用 history.replace：避免页面刷新，同时更新 URL。
- 去除尾部斜杠：防止 URL 重复和路径问题。
