### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#3]
Need enable Search function

* docs: https://docusaurus.io/zh-CN/docs/next/search

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/151113183-b36ef075-799d-4f12-a81a-4360fc72e2c4.png)

**Comment by qiaofeng1227** [comment]
[add  algolia](https://docusaurus.io/docs/search#using-local-search)

**Comment by qiaofeng1227** [comment]
每月10000条，合计每日300次搜索免费
![image](https://user-images.githubusercontent.com/43192516/151482087-f46ff2f3-e671-4386-a2aa-719b47d9d3d7.png)

**Comment by qiaofeng1227** [comment]
引入DocSearch有两种方式：
1. 整体引入
```docusaurus.config.js里加入配置
    algolia: {
      // The application ID provided by Algolia
      appId: '7OW3EQLSSO',

      // Public API key: it is safe to commit it
      apiKey: 'cdde477c72a2c884c51e7c28219a839a',

      indexName: 'websoft9',

      // Optional: see doc section below
      //contextualSearch: true,

      // Optional: Specify domains where the navigation should occur through window.location instead on history.push. Useful when our Algolia config crawls multiple documentation sites and we want to navigate with window.location.href to them.
      externalUrlRegex: 'http://8.142.3.195:3000',

      // Optional: Algolia search parameters
      //searchParameters: {},

      //... other Algolia params
    }
```
2. [单独页面引入](docusaurus.config.js)

**Comment by qiaofeng1227** [comment]
https://docusaurus.io/zh-CN/community/resources#community-plugins

**Comment by qiaofeng1227** [comment]
plugins: [require.resolve('docusaurus-lunr-search')]
![image](https://user-images.githubusercontent.com/43192516/152733266-227758ea-5148-4c60-aadb-a5dbe8617001.png)

plugins: [require.resolve("@cmfcmf/docusaurus-search-local")]
![image](https://user-images.githubusercontent.com/43192516/152735238-a9fe4d04-910d-4e6c-99fe-c71129c7d94c.png)

**Comment by qiaofeng1227** [comment]
https://github.com/algolia/docsearch-configs

**Comment by qiaofeng1227** [comment]
https://github.com/cmfcmf/docusaurus-search-local/issues/96

**Comment by qiaofeng1227** [comment]
complete

**Comment by qiaofeng1227** [comment]
https://github.com/Websoft9/docker-typesense

**Comment by zhaojing1987** [comment]
Add a Search Bar to the Documentation Site：
1、use the docusaurus-theme-search-typesense plugin to add a search bar to theDocusaurus site：
     npm install docusaurus-theme-search-typesense@next --save
     or
     yarn add docusaurus-theme-search-typesense@next
2、Add the following to your docusaurus.config.js file：
`{
  themes: ['docusaurus-theme-search-typesense'],
  themeConfig: {
    typesense: {
      typesenseCollectionName: 'websoft9', // Replace with your own doc site's name. Should match the collection name in the scraper settings.
      
      typesenseServerConfig: {
        nodes: [
          {
            host: 'xxx-1.a1.typesense.net',
            port: 443,
            protocol: 'https',
          },
        ],
        apiKey: 'xyz',
      },

      // Optional: Typesense search parameters: https://typesense.org/docs/0.21.0/api/documents.md#search-parameters
      typesenseSearchParameters: {},

      // Optional
      contextualSearch: true,
    },
  }
}`
