### ISSUE TITLE
文档关键部分完善

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/doc.websoft9.com#30]
根据新的docker安装方式，文档关键部分完善，国外平台更新审核时，可能会检查链接内容是否匹配

- [ ] Neo4j [英文] - 【升级】章节-未翻译
https://support.websoft9.com/en/docs/neo4j/admin

- [ ] kafka 【英文】-【端口】9091→9000-新方式有变化
https://support.websoft9.com/en/docs/kafka

- [ ] mongodb【英文】-【端口】9091→9090 &【安装-mangocompass】章节-新方式有变化
https://support.websoft9.com/en/docs/mongodb

- [ ] moodle【英文】- 【端口】9001？ & 汉译英未完整
https://support.websoft9.com/en/docs/moodle

**Comment by laozhou0731** [comment]
https://support.websoft9.com/en/docs/neo4j

**Comment by qiaofeng1227** [comment]
对应完毕
