### ISSUE TITLE
Improve current features of Odoo EN documentation

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/doc.websoft9.com#43]
**What type of your feature request?**  

- [ ] Add new features
- [x] Improve current features

https://support.websoft9.com/en/docs/odoo/admin
  
![image](https://user-images.githubusercontent.com/54173243/197981228-37c9de7f-6454-4fdc-9ee6-8ea366c322d2.png)

**Comment by qiaofeng1227** [comment]
translated
