### ISSUE TITLE
Improve codeserver  documentation

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/doc.websoft9.com#45]
已经完成初始化和参数设定。
因为考虑费用问题，目前已经停机，自行去阿里云后台开机即可。实例名：websoft9-codeserverdoc-CentOS7.

**Comment by Tooy1011** [comment]
1. code-server 使用入门以Python开发为例，无法运行python程序

- 实际：
![QQ截图20221101092234](https://user-images.githubusercontent.com/81067792/199142023-5b46e462-e09e-498f-b520-8edf14edad99.png)

- 文档：
![image](https://user-images.githubusercontent.com/81067792/199142176-17e65090-915d-4753-a355-324bc89d5cce.png)

2. code-server常用操作中多开发者范例，/data/wwwroot/user1/.env 文件未找到

- 实际：
![屏幕截图 2022-11-01 093556](https://user-images.githubusercontent.com/81067792/199142433-c7c263df-17c3-4f52-a60a-f1fbba52b8e7.png)

- 文档：
![image](https://user-images.githubusercontent.com/81067792/199142526-a2aa6bd1-b95a-48ef-be15-ba06a5dbb3bf.png)

**Comment by laozhou0731** [comment]
完成对应英文版修订
