### ISSUE TITLE
Improve drupal documentation

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/doc.websoft9.com#46]
已经完成初始化和参数设定。
因为考虑费用问题，目前已经停机，自行去阿里云后台开机即可。实例名：websoft9-drupaldoc-CentOS7.

**Comment by zl-go** [comment]
## 设置多语言
### 问题：点击进入【地区和语言】页面，没有所显示模块
实际:
![image](https://user-images.githubusercontent.com/62973206/199139359-3230951c-5f38-4755-9648-4fe4fd1c1692.png)
文档：
![image](https://user-images.githubusercontent.com/62973206/199141489-6d038f14-2369-45a2-bff0-b1dbe03e9e24.png)


## 安装扩展
### 问题：点进官方扩展搜索页面，与文档截图不一致
实际：
![image](https://user-images.githubusercontent.com/62973206/199139636-92165a9d-895c-4a2a-95fd-d6d5f8f8ac20.png)
文档：
![image](https://user-images.githubusercontent.com/62973206/199141515-f2246424-5bc5-43c4-a894-85586252500e.png)

### 问题：官方扩展页面没有download模块
实际：
![image](https://user-images.githubusercontent.com/62973206/199146566-8207c5c6-4bf4-4bfd-aa55-4996ef25409f.png)
文档：
![image](https://user-images.githubusercontent.com/62973206/199146608-e2b2e5c6-4325-4b45-a787-2f70211ee7f0.png)


## 更换域名
### 问题：根目录下没有文档中所说的.htaccess
实际：
![image](https://user-images.githubusercontent.com/62973206/199145236-5a84c69e-ab38-4bec-a4af-8b3b42b6d1c5.png)
文档：
![image](https://user-images.githubusercontent.com/62973206/199145312-de157fe4-af41-4f61-b1fc-f0ece0d838a1.png)

**Comment by laozhou0731** [comment]
完成对应英文版修订
