### ISSUE TITLE
Improve joomla documentation 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/doc.websoft9.com#53]
已经完成初始化和参数设定。
因为考虑费用问题，目前已经停机，自行去阿里云后台开机即可。实例名：websoft9-joomladoc-CentOS7.

**Comment by qiaofeng1227** [comment]
菜单位置完全不一样
![image](https://user-images.githubusercontent.com/43192516/199135404-b559bae8-1465-495a-9233-df19e268a08e.png)

**Comment by xyt52** [comment]
Joomla 扩展 导航栏位置完全不一样

操作结果：
![YR{EEXURP 7I 0G7GI~MRM](https://user-images.githubusercontent.com/93903193/199149940-25a68d32-ebec-47f8-99a9-e5bbf8e35b78.png)

文档：
![image](https://user-images.githubusercontent.com/93903193/199149987-3462e0c5-7021-45f7-8608-8c024c4aa9b8.png)

Joomla扩展 安装后，打开【扩展管理】>【模板管理】>【风格管理】。导航栏位置不同

操作结果：
![$H$B0W7SOT%16F{F @CEE6](https://user-images.githubusercontent.com/93903193/199150205-5feb63a5-bf3c-4318-af0a-aaa95a250ef9.png)

文档：
![image](https://user-images.githubusercontent.com/93903193/199150347-8eeb0b88-cdd7-40c0-b64c-8da84ea9dbaa.png)

Joomla Cache导航栏位置也发生改变

操作结果：
![()TKG0($HL3J1C8}DXDIW6V](https://user-images.githubusercontent.com/93903193/199150504-d37ef65b-3b28-4de3-a99f-21aa72a392ed.png)

文档：
![image](https://user-images.githubusercontent.com/93903193/199150549-bf0a82f6-90e8-4d46-8eda-5bb5f8247915.png)

**Comment by laozhou0731** [comment]
完成对应英文版修订
