### ISSUE TITLE
第四级标题右侧边栏显示

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#7]
类似：http://8.142.3.195:3002/docs/%E7%AE%A1%E7%90%86%E5%91%98/%E5%9F%BA%E7%A1%80%E5%B9%B3%E5%8F%B0/%E4%BA%91%E5%B9%B3%E5%8F%B0/%E5%8D%8E%E4%B8%BA%E4%BA%91/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

这种页面是由多个 #### 标题组成的，如何让第四级标题右侧边栏显示？

**Comment by qiaofeng1227** [comment]
[默认显示2,3级](https://docusaurus.io/docs/markdown-features/inline-toc)

**Comment by qiaofeng1227** [comment]
https://markdown-all-in-one.github.io/docs/guide/table-of-contents.html#overview
